### ISSUE TITLE
[App request] Homarr

### ISSUE THREAD

**Issue by zeroquinc** [saltyorg/Sandbox#179]
## Homarr

Homarr is a simple and lightweight homepage for your server, that helps you easily access all of your services in one place.
It integrates with the services you use to display information on the homepage (E.g. Show upcoming Sonarr/Radarr releases).

[Link to Homarr on GitHub](https://github.com/ajnart/homarr)

## Installation

```
version: '3'
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
    ports:
      - '7575:7575'
```
## Docs

[Link to Docs](https://homarr.dev/docs/about)

## Demo

https://homarr.ajnart.fr/

I know we already have a Heimdall role but would love to see a role of this as well as it is actively developed.
