### ISSUE TITLE
App Request: Cleanarr

### ISSUE THREAD

**Issue by Exile-boop** [saltyorg/Sandbox#229]
https://github.com/se1exin/Cleanarr

A simple UI to help find and delete duplicate and sample files from your Plex server.

**Comment by maximuskowalski** [comment]
https://hub.docker.com/r/selexin/cleanarr

```yaml
version: '3'

services:

  cleanarr:
    image: selexin/cleanarr:latest
    container_name: cleanarr
    hostname: cleanarr
    ports:
      - "5000:80"
    environment:
      - BYPASS_SSL_VERIFY=1
      - PLEX_TOKEN=somerandomstring
      - PLEX_BASE_URL=http://192.169.1.100:32400
      - LIBRARY_NAMES=Adult Movies;Kid Videos
    volumes:
      - /some/path/on/your/computer:/config
    restart: unless-stopped
    ```
