### ISSUE TITLE
App Request: dashdot

### ISSUE THREAD

**Issue by feavle** [saltyorg/Sandbox#232]
### **dash.**

A simple, modern server dashboard, primarily used by smaller private servers.

https://github.com/MauriceNino/dashdot

```
version: '3.5'

services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
```

### **Preview**

![screenshot](https://getdashdot.com/img/screenshot_darkmode.png)

### **Documentation**

https://getdashdot.com/docs/install

### **Demo**

https://dash.mauz.io/
