### ISSUE TITLE
Radarr Extended 

### ISSUE THREAD

**Issue by mtauberjr** [saltyorg/Sandbox#239]
https://github.com/RandomNinjaAtk/docker-radarr-extended

**Comment by owine** [comment]
Since this can just drop in to the existing radarr role in Saltbox using the inventory system, I don't see the need for a separate role. Some sample inventory entries were provided in the Discord.

```
radarr_docker_image: "randomninjaatk/radarr-extended:latest"
radarr_docker_envs_custom:
  enableAutoConfig: "true"
  enableRecyclarr: "true"
  enableQueueCleaner: "true"
  enableExtras: "true"
  extrasType: "all"
  extrasLanguages: "en-US,it-IT"
  extrasOfficialOnly: "false"
  extrasSingle: "false"
  extrasKodiCompatibility: "false"
  plexUrl: "https://plex.domain.tld"
  plexToken: "Token_Goes_Here"
```

@maximuskowalski let me know if you feel differently.
