### ISSUE TITLE
App Request: BudgE

### ISSUE THREAD

**Issue by bradmartti** [saltyorg/Sandbox#245]
https://github.com/linuxserver/budge

I don't have the skill set to create the role but I think it would make a great addition to saltbox if it works as intended. 

"BudgE (pronounced "budgie", like the bird) is an open source "budgeting with envelopes" personal finance app, taking inspiration from other tools such as [Aspire Budgeting](https://www.aspirebudget.com/), [budgetzero](https://budgetzero.io/), and [Buckets](https://www.budgetwithbuckets.com/)."

**Comment by maximuskowalski** [comment]
Compose file
```yml
---
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/budge/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    ```
    
    @bradmartti would you be interested in making the basic docs for this if someone creates the role?
