### ISSUE TITLE
jellystat

### ISSUE THREAD

**Issue by moooep** [saltyorg/Sandbox#253]
This app is for jellyfin what tautulli for plex is. I think it fits perfectly to saltbox: https://github.com/CyferShepard/Jellystat

**Comment by owine** [comment]
https://hub.docker.com/r/cyfershepard/jellystat

```
services:
  jellystat-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
  jellystat:
    image: cyfershepard/jellystat:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: 'my-secret-jwt-key'
    ports:
      - "3000:3000" #Server Port
      - "3004:3004" #websocket port
    volumes:
      - /app/backend/backup-data:/backup-data # Mounting the volume

    depends_on:
      - jellystat-db
networks:
  default:
```

Being a role with a database and given our upcoming restructure of all DB roles, this would probably be for the traefik3 branch only until that is merged.
