### ISSUE TITLE
App Request: Reiverr

### ISSUE THREAD

**Issue by blacroix** [saltyorg/Sandbox#349]
Hi

What about adding [Reiverr](https://github.com/aleksilassila/reiverr) as an alternative to Overseerr? It looks promising from what I see.

> Reiverr is a project that aims to create a single UI for interacting with TMDB, Jellyfin, Radarr and Sonarr, as well as be an alternative to Overseerr.

**Comment by owine** [comment]
https://github.com/aleksilassila/reiverr?tab=readme-ov-file#docker-compose
```
version: '3.8'

name: reiverr

services:
  reiverr:
    image: ghcr.io/aleksilassila/reiverr:latest
    container_name: reiverr
    ports:
      - 9494:9494
    volumes:
      - /path/to/appdata/config:/config
    restart: unless-stopped
```
